---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: promtail
  namespace: default
spec:
  minReadySeconds: 10
  template:
    metadata:
      labels:
        name: promtail
    spec:
      containers:
      - args:
        - -config.file=/etc/promtail/promtail.yml
        - -client.url=...
        image: kausal/promtail:master-503b52a
        imagePullPolicy: IfNotPresent
        name: promtail
        ports:
        - containerPort: 80
          name: http
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - mountPath: /etc/promtail
          name: promtail-config
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: mcdc
      serviceAccount: promtail
      volumes:
      - configMap:
          name: promtail-config
        name: promtail-config
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: mcdc
  updateStrategy:
    type: RollingUpdate
