{
  "name": "prometheus-ksonnet",
  "apiVersion": "0.0.1",
  "kind": "ksonnet.io/parts",
  "description": "Prometheus is an open-source systems monitoring and alerting toolkit.",
  "author": "Kausal <hello@kausal.co>",
  "contributors": [
    {
    "name": "Tom Wilkie",
    "email": "tom@kausal.co"
    },
  ],
  "repository": {
    "type": "git",
    "url": "https://github.com/kausal/public"
  },
  "bugs": {
    "url": "https://github.com/kausal/public/issues"
  },
  "keywords": [
    "Prometheus",
    "Monitoring",
    "Alerting",
  ],
  "quickStart": {
    "prototype": "co.kausal.pkg.prometheus",
    "componentName": "prometheus",
    "flags": {
      "namespace": "default",
    },
    "comment": "Run a complete Prometheus stack."
  },
  "license": "Apache 2.0"
}
